name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-preview:
    name: Test and Deploy Preview
    runs-on: ubuntu-latest
    
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4
      
      # Backend Tests
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, mysql, redis
          coverage: none
      
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan test
      
      # Frontend Tests and Preview Deploy
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: |
          npm run lint
          npm run test:run
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy Preview to Vercel
        working-directory: ./frontend
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_ENV
      
      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready!\n\nView deployment: ${process.env.DEPLOYMENT_URL}`
            })