name: Deploy

# CI/CDは現在無効化中 - 使用する際は下記のコメントアウトを解除してください
# on:
#   push:
#     branches: [ main ]

# マニュアル実行のみ有効
on:
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader

      - name: Create deployment archive
        run: |
          cd backend
          tar -czf ../backend-deploy.tar.gz \
            --exclude=node_modules \
            --exclude=tests \
            --exclude=.git \
            --exclude=storage/logs \
            --exclude=storage/framework/cache \
            --exclude=storage/framework/sessions \
            --exclude=storage/framework/views \
            .

      # TODO: Add your deployment method here
      # Example for SSH deployment:
      # - name: Deploy to server via SSH
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOY_USER }}
      #     key: ${{ secrets.DEPLOY_SSH_KEY }}
      #     script: |
      #       cd /path/to/your/app
      #       # Your deployment commands here

      # Example for AWS deployment:
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      #
      # - name: Deploy to AWS
      #   run: |
      #     # Your AWS deployment commands here

      # Example for Laravel Vapor:
      # - name: Deploy with Laravel Vapor
      #   run: |
      #     cd backend
      #     composer require laravel/vapor-cli --dev
      #     ./vendor/bin/vapor deploy production
      #   env:
      #     VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Placeholder for deployment
        run: |
          echo "🚀 Backend deployment placeholder"
          echo "Please configure your deployment method above"
          echo "Archive created: backend-deploy.tar.gz"

  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # TODO: Add your frontend deployment method here
      # Example for Netlify:
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.1
      #   with:
      #     publish-dir: './frontend/build'
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Example for Vercel:
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-args: '--prod'
      #     vercel-org-id: ${{ secrets.ORG_ID }}
      #     vercel-project-id: ${{ secrets.PROJECT_ID }}
      #     working-directory: ./frontend

      # Example for AWS S3 + CloudFront:
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      #
      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync frontend/build/ s3://${{ secrets.S3_BUCKET }} --delete
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      # Example for GitHub Pages:
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./frontend/build

      - name: Placeholder for deployment
        run: |
          echo "🚀 Frontend deployment placeholder"
          echo "Please configure your deployment method above"
          echo "Build completed successfully"

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()

    steps:
      - name: Notify deployment status
        run: |
          if [ "${{ needs.deploy-backend.result }}" == "success" ] && [ "${{ needs.deploy-frontend.result }}" == "success" ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
            exit 1
          fi

      # TODO: Add notification method (Slack, Discord, Email, etc.)
      # Example for Slack:
      # - name: Slack Notification
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     channel: '#deployments'
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      #   if: always()

      # Example for Discord:
      # - name: Discord Notification
      #   uses: sarisia/actions-status-discord@v1
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
      #     status: ${{ job.status }}
      #   if: always()